// app/layout.tsx

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopNav from "./TopNavigation/topnav";
import Footer from "@/components/Footer";
import ProvidersWrapper from "@/app/Components/ProvidersWrapper";
import React, { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Shipra Seeds",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="facebook-domain-verification"
          content="dqup99llq80yapwoq3ovi6zh7kbzio"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <ProvidersWrapper>
          <div className="absolute top-0 left-0 w-full z-50">
            <TopNav />
          </div>

          <main className="min-h-screen">
            <Suspense fallback={<div>Loading product data...</div>}>
              {children}
            </Suspense>
          </main>

          <Footer />
        </ProvidersWrapper>
      </body>
    </html>
  );
}
